TKWEB/Models/QUESTIONNAIRES.cs
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;


namespace TKWEB.Models
{
    public partial class QUESTIONNAIRES
    {
        public Guid ID { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy/MM/dd}", ApplyFormatInEditMode = true)]
        [DisplayName("1-日期(格式:西元年/月/日 2020/1/1) *")]
        [Required]
        public DateTime? DATES { get; set; }

        [DisplayName("2-工號 *")]
        [Required]
        public string NO { get; set; }

        [DisplayName("3-姓名 *")]
        [Required]
        public string NAME { get; set; }

        [DisplayName("4-部門 *")]
        [Required]
        public string DEP { get; set; }

        [DisplayName("5-請問24小時內，您與您同住的家屬/室友是否出現以下微狀(複選)? *")]
        [Required]
        public string QUESTION1 { get; set; }

        [DisplayName("6-承上題，如有症狀請簡短說明何時、何地、何人")]
        //[Required]
        public string QUESTION2 { get; set; }

        [DisplayName("7-請問24小時內您與您的同住的家屬/室友是否從其他國家入境台灣？ *")]
        [Required]
        public string QUESTION3 { get; set; }

        [DisplayName("8-承上題，簡短說明何時、何地、何人、班次?")]
        //[Required]
        public string QUESTION4 { get; set; }

        [DisplayName("9-請問24小時內您與您的同住的家屬/室友是否曾與已確診/疑似/正在接受檢驗之新型冠狀病毒肺炎病患有接觸？ *")]
        [Required]
        public string QUESTION5 { get; set; }

        [DisplayName("10-承上題，簡短說明何時接觸、何地接觸、何人接觸?")]
        //[Required]
        public string QUESTION6 { get; set; }

        [DisplayName("11-請問24小時內您與您的同住的家屬/室友是否曾前往非閉密空間但人潮擁擠的公共場所(無適當社交距離1M)，如旅遊地區、夜市、風景地區、寺廟等？ *")]
        [Required]
        public string QUESTION7 { get; set; }

        [DisplayName("12-承上題，簡短說明何時、何地、何人、共約幾人")]
        //[Required]
        public string QUESTION8 { get; set; }

        [DisplayName("13-請問24小時內您與您的同住的家屬/室友是否曾搭乘大眾交通運輸工具（公車、台鐵、高鐵、捷運、渡輪、客運、遊覽車…）*")]
        [Required]
        public string QUESTION9 { get; set; }

        [DisplayName("14-承上題，簡短說明何時、何地、何人、何種交通工具、班次?")]
        //[Required]
        public string QUESTION10 { get; set; }

        [DisplayName("15-其他想告知的事項")]
        //[Required]
        public string QUESTION11 { get; set; }

      
    }
}

TKWEB/Controllers/QUESTIONNAIRESController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TKWEB.Models;

namespace TKWEB.Controllers
{
    public class QUESTIONNAIRESController : Controller
    {
        private readonly TKWEBContext _context;

        public QUESTIONNAIRESController(TKWEBContext context)
        {
            _context = context;
        }

        // GET: QUESTIONNAIRES
        public async Task<IActionResult> Index()
        {
            return View(await _context.QUESTIONNAIRES.ToListAsync());
        }

        /// <summary>
        /// 新增填寫完成頁
        /// </summary>
        /// <returns></returns>
        public async Task<IActionResult> OK()
        {
            return View(await _context.QUESTIONNAIRES.ToListAsync());
        }

        // GET: QUESTIONNAIRES/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var qUESTIONNAIRES = await _context.QUESTIONNAIRES
                .FirstOrDefaultAsync(m => m.ID == id);
            if (qUESTIONNAIRES == null)
            {
                return NotFound();
            }

            return View(qUESTIONNAIRES);
        }

        // GET: QUESTIONNAIRES/Create
        public IActionResult Create()
        {
            //ViewBag讀取DB的方法，DB、TABLE跟MODEL要先建立好才可以用
            //List<QUESTIONDEP> QUESTIONDEPLIST = new List<QUESTIONDEP>();
            //QUESTIONDEPLIST = (from QUESTIONDEP in _context.QUESTIONDEP select QUESTIONDEP).ToList(); 
            //ViewBag.QUESTIONDEPLIST = QUESTIONDEPLIST.Select(c => new SelectListItem { Value = c.DEPID, Text = c.DEPNAME }).ToList();

            //ViewBag直接設定
            var DEPselectList = new List<SelectListItem>()
            {
                new SelectListItem {Text="總經理室(含經營分析中心、資訊管理中心、人資管理中心、新事業發展中心)", Value="總經理室(含經營分析中心、資訊管理中心、人資管理中心、新事業發展中心)" },
                new SelectListItem {Text="職安室", Value="職安室" },
                new SelectListItem {Text="管理部(含總務課)", Value="管理部(含總務課)" },
                new SelectListItem {Text="財務部(含成本課、會計課、財務課)", Value="財務部(含成本課、會計課、財務課)" },
                new SelectListItem {Text="資材部(含採購課)", Value="資材部(含採購課)" },
                new SelectListItem {Text="研發部(含產品開發課、研發課)", Value="研發部(含產品開發課、研發課)" },
                new SelectListItem {Text="品保部(含文管中心、品檢課、品保課)", Value="品保部(含文管中心、品檢課、品保課)" },
                new SelectListItem {Text="生產部(含倉儲課、工程課、製造課、手工課、內包課、外包課、生管課)", Value="生產部(含倉儲課、工程課、製造課、手工課、內包課、外包課、生管課)" },
                new SelectListItem {Text="事業拓展部(含大陸業務課、國外業務課、國內業務課)", Value="事業拓展部(含大陸業務課、國外業務課、國內業務課)" },
                new SelectListItem {Text="營銷部(含電子商務課、門市課、觀光課)", Value="營銷部(含電子商務課、門市課、觀光課)" },
                new SelectListItem {Text="行銷企劃部(含行銷企劃課、設計課)", Value="行銷企劃部(含行銷企劃課、設計課)" }
            };

            //預設選擇哪一筆
            //selectList.Where(q => q.Value == "value-2").First().Selected = true;
            ViewBag.DEPselectList = DEPselectList;

            // Build your models (example)
            var STATUSList = new List<SelectListItem>()
            {
             
                new SelectListItem {Text="發燒（額溫高於37.5度、耳溫高於38度、腋溫高於38度）", Value="發燒（額溫高於37.5度、耳溫高於38度、腋溫高於38度）" },
                new SelectListItem {Text="乾咳", Value="乾咳" },
                new SelectListItem {Text="嗅、味覺異常", Value="嗅、味覺異常" },
                new SelectListItem {Text="呼吸急促或困難", Value="呼吸急促或困難" },
                new SelectListItem {Text="不明原因腹瀉", Value="不明原因腹瀉" },
                new SelectListItem {Text="有呼吸道症狀（鼻塞、流鼻水、咳嗽）", Value="有呼吸道症狀（鼻塞、流鼻水、咳嗽）" },
                new SelectListItem {Text="否,以上皆無", Value="否,以上皆無" }

            };
            // Store your model in the ViewBag
            ViewBag.STATUSList = STATUSList;

            return View();
            
        }

        // POST: QUESTIONNAIRES/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,DATES,NO,NAME,DEP,QUESTION1,QUESTION2,QUESTION3,QUESTION4,QUESTION5,QUESTION6,QUESTION7,QUESTION8,QUESTION9,QUESTION10,QUESTION11")] QUESTIONNAIRES qUESTIONNAIRES)
        {            
            if (ModelState.IsValid)
            {
                //qUESTIONNAIRES.QUESTION1 = "ABCD";


                qUESTIONNAIRES.ID = Guid.NewGuid();
                _context.Add(qUESTIONNAIRES);
                await _context.SaveChangesAsync();
                //return RedirectToAction(nameof(Index));
                return View("OK");
            }

            //return View(qUESTIONNAIRES);
            return View("OK");
        }

        // GET: QUESTIONNAIRES/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var qUESTIONNAIRES = await _context.QUESTIONNAIRES.FindAsync(id);
            if (qUESTIONNAIRES == null)
            {
                return NotFound();
            }
            return View(qUESTIONNAIRES);
        }

        // POST: QUESTIONNAIRES/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("ID,DATES,NO,NAME,DEP,QUESTION1,QUESTION2,QUESTION3,QUESTION4,QUESTION5,QUESTION6,QUESTION7,QUESTION8,QUESTION9,QUESTION10,QUESTION11")] QUESTIONNAIRES qUESTIONNAIRES)
        {
            if (id != qUESTIONNAIRES.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(qUESTIONNAIRES);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!QUESTIONNAIRESExists(qUESTIONNAIRES.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(qUESTIONNAIRES);
        }

        // GET: QUESTIONNAIRES/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var qUESTIONNAIRES = await _context.QUESTIONNAIRES
                .FirstOrDefaultAsync(m => m.ID == id);
            if (qUESTIONNAIRES == null)
            {
                return NotFound();
            }

            return View(qUESTIONNAIRES);
        }

        // POST: QUESTIONNAIRES/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var qUESTIONNAIRES = await _context.QUESTIONNAIRES.FindAsync(id);
            _context.QUESTIONNAIRES.Remove(qUESTIONNAIRES);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool QUESTIONNAIRESExists(Guid id)
        {
            return _context.QUESTIONNAIRES.Any(e => e.ID == id);
        }
    }
}

TKWEB/Views/QUESTIONNAIRES/Create.cshtml
@model TKWEB.Models.QUESTIONNAIRES

    <header>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <LINK href="../css/TKWEB.css" type="text/css" rel="stylesheet">
    </header>

@{
    ViewData["Title"] = "Create";

    List<SelectListItem> listItems = new List<SelectListItem>();
    listItems.Add(new SelectListItem
    {
        Text = "ITEM-1",
        Value = "ITEM-1"
    });
    listItems.Add(new SelectListItem
    {
        Text = "ITEM-2",
        Value = "ITEM-2"
    });
    listItems.Add(new SelectListItem
    {
        Text = "ITEM-3",
        Value = "ITEM-3"
    });
}
<body>
    <div class="form-group">
        <h1>每日防疫問卷</h1>
        <h4>周一至周日都需填寫一次 (若未填寫或有狀況，上班日將會有防疫人員電話詢問)</h4>
        <h4>* 表示必填</h4>
        <h4>(日班請於每日早上6~10點前填寫完畢)</h4>
        <h4>(夜班請於每日下午12點~16點前填寫完畢)</h4>
    </div>
   
    <hr />
    <div class="container-fluid">
        <div class="col-md-4">
            <form asp-action="Create">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="DATES" class="control-label"></label>
                    <input asp-for="DATES" class="form-control" />
                    <span asp-validation-for="DATES" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="NO" class="control-label"></label>
                    <input asp-for="NO" class="form-control" />
                    <span asp-validation-for="NO" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="NAME" class="control-label"></label>
                    <input asp-for="NAME" class="form-control" />
                    <span asp-validation-for="NAME" class="text-danger"></span>
                </div>
                <div class="form-group-DEP">
                    <label asp-for="DEP" class="control-label"></label>
                    <div class="DropDownListFor">
                        @*@Html.DropDownListFor(model => model.DEP, listItems, "請選擇")*@

                        @Html.DropDownListFor(model => model.DEP, new SelectList(ViewBag.DEPselectList, "Value", "Text"))

                    </div>
                    @*<input asp-for="DEP" class="form-control" id="selector">*@
                    <span asp-validation-for="DEP" class="text-danger"></span>
                </div>
                <br />
                <div class="form-group-QUESTION1">
                    <label asp-for="QUESTION1" class="control-label-QUESTION1"></label>

                    @foreach (var STATUS in ViewBag.STATUSList)
                    {
                        <div class="checkbox">
                            <input id="@STATUS.Text" type="checkbox" name="STATUS" value="@STATUS.Value" />
                            <label for="@STATUS.Text">
                                @STATUS.Text
                            </label>
                        </div>
                    }
                    @Html.HiddenFor(model => model.QUESTION1)
                    @*<input asp-for="QUESTION1" class="form-control" />*@
                    <span asp-validation-for="QUESTION1" class="text-danger"></span>

                </div>
                <br />
                <div class="form-group-QUESTION1">
                    <label asp-for="QUESTION2" class="control-label"></label>
                    <input asp-for="QUESTION2" class="form-control" />
                    <span asp-validation-for="QUESTION2" class="text-danger"></span>
                </div>
                <br />
                <div class="form-group-QUESTION1">
                    <label asp-for="QUESTION3" class="control-label"></label>
                    <br></br>
                    @Html.RadioButtonFor(model => model.QUESTION3, "否")
                    否
                    <br></br>
                    @Html.RadioButtonFor(model => model.QUESTION3, "是，請於下題填寫何時、何地、何人、班次")
                    是，請於下題填寫何時、何地、何人、班次

                    @*<input asp-for="QUESTION3" class="form-control" />*@
                    <span asp-validation-for="QUESTION3" class="text-danger"></span>
                </div>
                <br />
                <div class="form-group-QUESTION1">
                    <label asp-for="QUESTION4" class="control-label"></label>
                    <input asp-for="QUESTION4" class="form-control" />
                    <span asp-validation-for="QUESTION4" class="text-danger"></span>
                </div>
                <br />
                <div class="form-group-QUESTION1">
                    <label asp-for="QUESTION5" class="control-label"></label>
                    <br></br>
                    @Html.RadioButtonFor(model => model.QUESTION5, "否")
                    否
                    <br></br>
                    @Html.RadioButtonFor(model => model.QUESTION5, "是，請於下題填寫何時接觸、何地接觸、何人接觸")
                    是，請於下題填寫何時接觸、何地接觸、何人接觸
                    <span asp-validation-for="QUESTION5" class="text-danger"></span>
                </div>
                <br />
                <div class="form-group-QUESTION1">
                    <label asp-for="QUESTION6" class="control-label"></label>
                    <input asp-for="QUESTION6" class="form-control" />
                    <span asp-validation-for="QUESTION6" class="text-danger"></span>
                </div>
                <br />
                <div class="form-group-QUESTION1">
                    <label asp-for="QUESTION7" class="control-label"></label>
                    <br></br>
                    @Html.RadioButtonFor(model => model.QUESTION7, "否")
                    否
                    <br></br>
                    @Html.RadioButtonFor(model => model.QUESTION7, "是，請於下題填寫何時、何地、何人、共約幾人")
                    是，請於下題填寫何時、何地、何人、共約幾人
                    <span asp-validation-for="QUESTION7" class="text-danger"></span>
                </div>
                <br />
                <div class="form-group-QUESTION1">
                    <label asp-for="QUESTION8" class="control-label"></label>
                    <input asp-for="QUESTION8" class="form-control" />
                    <span asp-validation-for="QUESTION8" class="text-danger"></span>
                </div>
                <br />
                <div class="form-group-QUESTION1">
                    <label asp-for="QUESTION9" class="control-label"></label>
                    <br></br>
                    @Html.RadioButtonFor(model => model.QUESTION9, "否")
                    否
                    <br></br>
                    @Html.RadioButtonFor(model => model.QUESTION9, "是，請於下題填寫何時、何地、何人、何種交通工具、班次")
                    是，請於下題填寫何時、何地、何人、何種交通工具、班次
                    <span asp-validation-for="QUESTION9" class="text-danger"></span>
                </div>
                <br />
                <div class="form-group-QUESTION1">
                    <label asp-for="QUESTION10" class="control-label"></label>
                    <input asp-for="QUESTION10" class="form-control" />
                    <span asp-validation-for="QUESTION10" class="text-danger"></span>
                </div>
                <br />
                <div class="form-group-QUESTION1">
                    <label asp-for="QUESTION11" class="control-label"></label>
                    <input asp-for="QUESTION11" class="form-control" />
                    <span asp-validation-for="QUESTION11" class="text-danger"></span>
                </div>
                <br />
                <div class="form-group">
                    <input type="submit" value="提交" class="btn btn-primary" onclick="update()" />
                </div>
            </form>
        </div>
    </div>
</body>

<script>
    function update(arg) {
        var CHECKBOXLIST = ""
        //Iterating the collection of checkboxes which checked marked
        $('input[type=checkbox][name=STATUS]').each(function () {
            if (this.checked) {
                CHECKBOXLIST = CHECKBOXLIST + $(this).val() + ","
                //assign set value to hidden field
                $('#QUESTION1').val(CHECKBOXLIST);
            }
        });

    }
</script>

<div>
    @*<a asp-action="Index">Back to List</a>*@
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

TKWEB/Views/QUESTIONNAIRES/Delete.cshtml
@model TKWEB.Models.QUESTIONNAIRES

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>QUESTIONNAIRES</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DATES)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DATES)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NO)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NO)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NAME)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NAME)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DEP)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DEP)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.QUESTION1)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.QUESTION1)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.QUESTION2)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.QUESTION2)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.QUESTION3)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.QUESTION3)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.QUESTION4)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.QUESTION4)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.QUESTION5)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.QUESTION5)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.QUESTION6)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.QUESTION6)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.QUESTION7)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.QUESTION7)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.QUESTION8)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.QUESTION8)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.QUESTION9)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.QUESTION9)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.QUESTION10)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.QUESTION10)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.QUESTION11)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.QUESTION11)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

TKWEB/Views/QUESTIONNAIRES/Details.cshtml
@model TKWEB.Models.QUESTIONNAIRES

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>QUESTIONNAIRES</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DATES)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DATES)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NO)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NO)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NAME)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NAME)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DEP)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DEP)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.QUESTION1)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.QUESTION1)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.QUESTION2)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.QUESTION2)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.QUESTION3)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.QUESTION3)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.QUESTION4)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.QUESTION4)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.QUESTION5)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.QUESTION5)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.QUESTION6)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.QUESTION6)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.QUESTION7)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.QUESTION7)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.QUESTION8)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.QUESTION8)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.QUESTION9)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.QUESTION9)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.QUESTION10)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.QUESTION10)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.QUESTION11)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.QUESTION11)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.ID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

TKWEB/Views/QUESTIONNAIRES/OK.cshtml
@model IEnumerable<TKWEB.Models.QUESTIONNAIRES>

    <header>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <LINK href="../css/TKWEB.css" type="text/css" rel="stylesheet">
    </header>

@{
    ViewData["Title"] = "完成";
}

<body>
    <div style="width:auto;height:200px;text-align:left;line-height:100px; font-size: 36px;">
        @*<div class="finishdiv">*@
        <p>每日防疫問卷</p>
        <p style="font-size: 18px;">我們已經收到您回覆的表單。</p>
        <a style="font-size: 18px;" asp-area="" asp-controller="QUESTIONNAIRES" asp-action="Create">提交其他回應</a>
    </div>
</body>