TKWEB/Controllers/HridworkhrsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using TKWEB.Models;


namespace TKWEB.Controllers
{
    public class HridworkhrsController : Controller
    {
        private readonly TKWEBContext _context;

        public HridworkhrsController(TKWEBContext context)
        {
            _context = context;
        }

        [Authorize(Roles = "Admin,Normal,102400,102500")]
        // GET: Hridworkhrs
        public async Task<IActionResult> Index(string STARTDATES, string ENDDATES)
        {
            string query = null;


            var IdentityNAME = User.Identity.Name;
            var IdentityNAMEARRAY = IdentityNAME.ToString().Split("@");
            var SUERNAME = IdentityNAMEARRAY[0].ToString();

            var user = new SqlParameter("user", SUERNAME);
            var sdats = new SqlParameter("sdats", STARTDATES);
            var edats = new SqlParameter("edats", ENDDATES);


            if (!String.IsNullOrEmpty(STARTDATES) && !String.IsNullOrEmpty(ENDDATES))
            {
                query = "SELECT [ID],[WROKDATES],[LOGINID],[WORKID],[HRS] FROM [TKWEB].[dbo].[HRIDWORKHRS]  WHERE [LOGINID]=@user AND CONVERT(NVARCHAR,[WROKDATES],112)>=@sdats AND CONVERT(NVARCHAR,[WROKDATES],112)<=@edats  ORDER BY [WROKDATES] DESC ";
                var result = await _context.Hridworkhrs.FromSqlRaw(query, user, sdats, edats).ToListAsync();

                return View(result);

            }
            else
            {
                query = "SELECT TOP 5 [ID],[WROKDATES],[LOGINID],[WORKID],[HRS] FROM [TKWEB].[dbo].[HRIDWORKHRS]  WHERE [LOGINID]=@user AND CONVERT(NVARCHAR,[WROKDATES],112) LIKE SUBSTRING(CONVERT(NVARCHAR,GETDATE(),112),1,6)+'%'  ORDER BY [WROKDATES] DESC ";
                var result = await _context.Hridworkhrs.FromSqlRaw(query, user).ToListAsync();

                return View(result);
            }

            //return View(await _context.Hridworkhrs.Where(s => s.Loginid == SUERNAME.ToString()).ToListAsync());
            //return View(await _context.Hridworkhrs.ToListAsync());
        }

        // GET: Hridworkhrs/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var hridworkhrs = await _context.Hridworkhrs
                .FirstOrDefaultAsync(m => m.Id == id);
            if (hridworkhrs == null)
            {
                return NotFound();
            }

            return View(hridworkhrs);
        }

        // GET: Hridworkhrs/Create
        public IActionResult Create()
        {
            var IdentityNAME = User.Identity.Name;
            var IdentityNAMEARRAY = IdentityNAME.ToString().Split("@");
            var SUERNAME = IdentityNAMEARRAY[0].ToString();

            ViewBag.Name = SUERNAME.ToString();

            var query = (from Hrworks in _context.Hrwork
                         join Hrrolework in _context.Hrrolework on Hrworks.Workid equals Hrrolework.Workid
                         join aspNetRoles in _context.AspNetRoles on Hrrolework.Role equals aspNetRoles.Name
                         join aspNetUserRoles in _context.AspNetUserRoles on aspNetRoles.Id equals aspNetUserRoles.RoleId
                         join aspNetUsers in _context.AspNetUsers on aspNetUserRoles.UserId equals aspNetUsers.Id
                         where aspNetUsers.UserName == IdentityNAME.ToString()
                         select new
                         {
                             Workid = Hrworks.Workid,
                             Workname = Hrworks.Workname,
                         }).ToList();

            ViewBag.Hrworks = query.Select(c => new SelectListItem { Value = c.Workname.ToString(), Text = c.Workname }).ToList();


            //ViewBag.Locations = _context.Hrwork.Select(c => new SelectListItem { Value = c.Workid.ToString(), Text = c.Workname }).ToList();

            ////Creating generic list
            //List<SelectListItem> ObjList = new List<SelectListItem>()
            //{
            //    new SelectListItem { Text = "Latur", Value = "1" },
            //    new SelectListItem { Text = "Pune", Value = "2" },
            //    new SelectListItem { Text = "Mumbai", Value = "3" },
            //    new SelectListItem { Text = "Delhi", Value = "4" },

            //};
            ////Assigning generic list to ViewBag
            //ViewBag.Locations = ObjList;

            return View();
        }

        // POST: Hridworkhrs/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Wrokdates,Loginid,Workid,Hrs")] Hridworkhrs hridworkhrs)
        {
            if (ModelState.IsValid)
            {
                hridworkhrs.Id = Guid.NewGuid();
                _context.Add(hridworkhrs);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(hridworkhrs);
        }

        // GET: Hridworkhrs/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var hridworkhrs = await _context.Hridworkhrs.FindAsync(id);
            if (hridworkhrs == null)
            {
                return NotFound();
            }
            return View(hridworkhrs);
        }

        // POST: Hridworkhrs/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("Id,Wrokdates,Loginid,Workid,Hrs")] Hridworkhrs hridworkhrs)
        {
            if (id != hridworkhrs.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(hridworkhrs);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!HridworkhrsExists(hridworkhrs.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(hridworkhrs);
        }

        // GET: Hridworkhrs/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var hridworkhrs = await _context.Hridworkhrs
                .FirstOrDefaultAsync(m => m.Id == id);
            if (hridworkhrs == null)
            {
                return NotFound();
            }

            return View(hridworkhrs);
        }

        // POST: Hridworkhrs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var hridworkhrs = await _context.Hridworkhrs.FindAsync(id);
            _context.Hridworkhrs.Remove(hridworkhrs);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool HridworkhrsExists(Guid id)
        {
            return _context.Hridworkhrs.Any(e => e.Id == id);
        }
    }
}

TKWEB/Controllers/REPORTController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using TKWEB.Models;

namespace TKWEB.Controllers
{
    public class REPORTController : Controller
    {
        private readonly TKWEBContext _context;

        public REPORTController(TKWEBContext context)
        {
            _context = context;
        }

        [Authorize(Roles = "Admin,Normal,102400")]
        public async Task<IActionResult> Index(string STARTDATES,string ENDDATES)
        {
            string query=null;
           

            var IdentityNAME = User.Identity.Name;
            var IdentityNAMEARRAY = IdentityNAME.ToString().Split("@");
            var SUERNAME = IdentityNAMEARRAY[0].ToString();

            var user = new SqlParameter("user", SUERNAME);
            var sdats = new SqlParameter("sdats", STARTDATES);
            var edats = new SqlParameter("edats", ENDDATES);


            if (!String.IsNullOrEmpty(STARTDATES)&& !String.IsNullOrEmpty(ENDDATES))
            {
                query = "SELECT [ID],[WROKDATES],[LOGINID],[WORKID],[HRS] FROM [TKWEB].[dbo].[HRIDWORKHRS]  WHERE [LOGINID]=@user AND CONVERT(NVARCHAR,[WROKDATES],112)>=@sdats AND CONVERT(NVARCHAR,[WROKDATES],112)<=@edats  ORDER BY [WROKDATES] DESC ";
                var result = await _context.Hridworkhrs.FromSqlRaw(query, user, sdats, edats).ToListAsync();

                return View(result);

            }
            else 
            {
                query = "SELECT TOP 1 [ID],[WROKDATES],[LOGINID],[WORKID],[HRS] FROM [TKWEB].[dbo].[HRIDWORKHRS]  WHERE [LOGINID]=@user AND CONVERT(NVARCHAR,[WROKDATES],112) LIKE SUBSTRING(CONVERT(NVARCHAR,GETDATE(),112),1,6)+'%'  ORDER BY [WROKDATES] DESC ";
                var result = await _context.Hridworkhrs.FromSqlRaw(query, user).ToListAsync();

                return View(result);
            }
           
            

            //return View(await _context.Hridworkhrs.Where(s => s.Loginid == SUERNAME.ToString()).ToListAsync());
            //return View(await _context.Hridworkhrs.ToListAsync());
        }

     

    }
}

TKWEB/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TKWEB</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TKWEB</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            @if (User.Identity.IsAuthenticated)
                            {
                                @if (User.IsInRole("Admin"))
                                {
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Hridworkhrs" asp-action="Index">Hridworkhrs</a>
                                }

                            }

                        </li>
                        <li class="nav-item">
                            @*<a class="nav-link text-dark" asp-area="" asp-controller="QUESTIONNAIRES" asp-action="Index">問卷</a>*@
                            <a class="nav-link text-dark" asp-area="" asp-controller="QUESTIONNAIRES" asp-action="Create">問卷</a>
                        </li>
                        @*<li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Hridworkhrs" asp-action="Index">工時記錄</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="REPORT" asp-action="Index">報表</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="EventViewModels" asp-action="Index">EventViewModels</a>
                        </li>*@
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - TKWEB - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>